# Node.js
- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '6'
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
 - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
